[[redirects]]
  from = "/*"
  # to = "https://origin.robnot.us.kg/"
  to = "http://221.226.197.181:25803/:splat"
  status = 200
  # force = true
  headers = {X-From = "Netlify", X-Original-Host = "{host}", X-Original-Path = ":splat"}
