[[redirects]]
  from = "https://:domain.robnot.us.kg/*"
  # to = "https://origin.robnot.us.kg/"
  to = "http://221.226.197.181:25803/host=:domain&path=:splat"
  status = 200
  # force = true
  headers = {X-From = "Netlify"}
